const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '../src/components/react-mindmap-editor')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

const editor = read('index.js')
const panel = read('components/executionFloatingPanels.js')
const view = read('view/index.js')
const styles = read('index.scss')
const utils = read('executionPanelUtils.js')
const core = read('assets/kityminder-core/kityminder.core.js')

assert(editor.includes('mindmap-context-menu ${'), '空白处右键菜单应使用级联浮层')
assert(editor.includes('className="mindmap-context-submenu"'), '展开入口应打开二级层级菜单')
assert(editor.includes('x: e.originEvent.clientX - containerRect.left'), '右键菜单应定位到鼠标位置')
assert(utils.includes("if (node.data.expandState == null) node.data.expandState = 'expand'"), '首次进入应默认展开且保留已有折叠状态')
assert(editor.includes('showToolBar: false'), '外观菜单默认应为折叠状态')
assert(!editor.includes('<TabPane tab="思路"'), '不应继续展示“思路”入口')
assert(editor.includes('className="mindmap-history-actions"'), '撤销重做应固定在脑图左上角')
assert(!view.includes('expandMenu'), '视图工具栏不应继续提供展开菜单')
assert(panel.includes('renderExecutionStatusIcon(item)'), '悬浮窗结果按钮应使用统一状态图标')
assert(!panel.includes('<Tooltip title={item.label}'), '结果按钮不应被 Tooltip 包装导致禁用态缩宽')
assert(panel.includes('title={item.label}'), '结果按钮应保留原生提示')
assert(utils.includes('<svg class="execution-status-icon'), '结果状态应使用统一 SVG 图标')
assert(styles.includes('grid-auto-rows: 38px'), '结果按钮选中前后应保持固定高度')
assert(styles.includes('> span {') === false || styles.includes('height: 38px'), '结果网格单元应固定高度')
assert(styles.includes('box-shadow: none;') && styles.includes('&.active'), '选中态不应改变按钮外部尺寸')
assert(styles.includes('.mindmap-context-submenu'), '展开二级菜单应在一级菜单右侧显示')
assert(styles.includes('left: calc(100% + 6px)'), '级联菜单应从一级菜单右侧展开')
assert(!editor.includes("label: '撤销',\n      key: 'Ctrl + Z'"), '节点右键菜单不应包含撤销')
assert(!editor.includes("label: '重做',\n      key: 'Ctrl + Y'"), '节点右键菜单不应包含重做')
assert(!editor.includes("label: '结果'"), '节点右键菜单不应包含标记结果')
assert(core.includes("'root-background': '#e7f1ff'"), '根节点应使用浅蓝背景')
assert(core.includes("'sub-background': '#f3f8ff'"), '末级节点应使用浅蓝背景')
assert(core.includes('expanderOffset'), '连接线应从折叠按钮右侧开始')
assert(core.includes("pathData.push('q'"), '连接线折角应使用圆角曲线')

console.log('execution UI regression checks passed')
