const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '../src/components/react-mindmap-editor')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

const editor = read('index.js')
const panel = read('components/executionFloatingPanels.js')
const view = read('view/index.js')
const styles = read('index.scss')
const doGroupStyles = read('toolbar/DoGroup.scss')
const utils = read('executionPanelUtils.js')
const core = read('assets/kityminder-core/kityminder.core.js')
const colorPicker = read('components/colorPicker.js')
const constants = read('constants/index.js')
const language = read('assets/lang/lang.zh-cn.js')
const documentTemplate = fs.readFileSync(path.resolve(__dirname, '../src/pages/document.ejs'), 'utf8')
const favicon = fs.readFileSync(path.resolve(__dirname, '../public/favicon.svg'), 'utf8')

assert(editor.includes('mindmap-context-menu ${'), '空白处右键菜单应使用级联浮层')
assert(editor.includes('className="mindmap-context-submenu"'), '展开入口应打开二级层级菜单')
assert(editor.includes('x: e.originEvent.clientX - containerRect.left'), '右键菜单应定位到鼠标位置')
assert(utils.includes("if (node.data.expandState == null) node.data.expandState = 'expand'"), '首次进入应默认展开且保留已有折叠状态')
assert(editor.includes('showToolBar: false'), '外观菜单默认应为折叠状态')
assert(!editor.includes('<TabPane tab="思路"'), '不应继续展示“思路”入口')
assert(editor.includes('className="mindmap-history-actions"'), '撤销重做应固定在脑图左上角')
assert(styles.includes('.mindmap-history-actions {\n  position: absolute;\n  top: 8px;'), '撤销重做应上移到在线人数同一行')
assert(doGroupStyles.includes('width: 32px;') && doGroupStyles.includes('height: 32px;'), '撤销重做应使用一致的 32px 图标按钮')
assert(doGroupStyles.includes('border: 1px solid #e2e8f0;'), '撤销重做应使用独立的浅灰边框按钮')
assert(doGroupStyles.includes('border-radius: 10px;'), '撤销重做应使用统一的柔和圆角')
assert(doGroupStyles.includes('background: #fff;'), '撤销重做默认应使用白色按钮背景')
assert(!styles.includes('.do-group .ant-btn-link'), '撤销重做的视觉样式应只由共享工具组件维护，避免尺寸冲突')
assert(!view.includes('expandMenu'), '视图工具栏不应继续提供展开菜单')
assert(panel.includes('renderExecutionStatusIcon(item)'), '悬浮窗结果按钮应使用统一状态图标')
assert(!panel.includes('<Tooltip title={item.label}'), '结果按钮不应被 Tooltip 包装导致禁用态缩宽')
assert(panel.includes('title={item.label}'), '结果按钮应保留原生提示')
assert(utils.includes('<svg class="execution-status-icon'), '结果状态应使用统一 SVG 图标')
assert(styles.includes('grid-auto-rows: 38px'), '结果按钮选中前后应保持固定高度')
assert(styles.includes('> span {') === false || styles.includes('height: 38px'), '结果网格单元应固定高度')
assert(styles.includes('box-shadow: none;') && styles.includes('&.active'), '选中态不应改变按钮外部尺寸')
assert(styles.includes('.mindmap-context-submenu'), '展开二级菜单应在一级菜单右侧显示')
assert(styles.includes('left: calc(100% + 6px)'), '级联菜单应从一级菜单右侧展开')
assert(!editor.includes("label: '撤销',\n      key: 'Ctrl + Z'"), '节点右键菜单不应包含撤销')
assert(!editor.includes("label: '重做',\n      key: 'Ctrl + Y'"), '节点右键菜单不应包含重做')
assert(!editor.includes("label: '结果'"), '节点右键菜单不应包含标记结果')
assert(core.includes("'root-background': '#e7f1ff'"), '根节点应使用浅蓝背景')
assert(core.includes("'main-background': '#f4f8ff'"), '一级节点应使用极浅蓝背景')
assert(core.includes("'sub-background': '#ffffff'"), '末级节点应使用白色背景避免整图铺蓝')
assert(core.includes('expanderOffset'), '连接线应从折叠按钮右侧开始')
const polyConnector = core.slice(core.indexOf("connect.register('poly'"), core.indexOf('//src/connect/under.js'))
assert(polyConnector.includes('var radius = Math.min(12'), '折线连接器必须在使用圆角半径前完成定义')
assert(polyConnector.includes("pathData.push('h', trunkOffset);\n            pathData.push('v', verticalDistance - verticalDirection * radius);\n            pathData.push('q', 0, verticalDirection * radius, radius, verticalDirection * radius);"), '右向连接线只能圆下一级节点入口前的最后一个折角')
assert(!polyConnector.includes("pathData.push('q', radius, 0, radius"), '父节点出来后的第一个折角应恢复直角')
assert(!editor.includes('<TabPane tab="视图"'), '工具栏不应继续展示视图入口')
assert(editor.includes('<MindMapSearch key="search" minder={minder} />'), '搜索框应移动到在线人数左侧')
assert(!editor.includes('<TabPane tab="外观"'), '外观不应继续占用左侧页签入口')
assert(editor.includes('<span>外观</span>'), '外观入口应占用原展开收起按钮的位置')
assert(styles.includes('> .ant-tabs-bar .ant-tabs-nav-container'), '原外观页签位置不应留下空白入口')
assert(!editor.includes('className="mindmap-back-button"'), '返回按钮不应放在在线人数工具栏')
assert(styles.includes('background: #fff;') && styles.includes('z-index: 80;'), '加载遮罩应完全遮住脑图，仅显示 loading')
assert(colorPicker.includes("'#edf5ff'"), '节点背景色应提供浅蓝色快捷配置')
assert(constants.includes("'byte-blue': '浅蓝色'"), 'ByteBlue 主题入口应显示为中文“浅蓝色”')
assert(language.includes("'byte-blue': '浅蓝色'"), '脑图语言包应将 ByteBlue 显示为中文“浅蓝色”')
assert(documentTemplate.includes('href="/favicon.svg"'), '网页标签应使用新的平台 favicon')
assert(favicon.includes('aria-label="TestCaseManage"'), '网页标签 Logo 应与当前平台名称相关')

const caseMgt = fs.readFileSync(path.resolve(__dirname, '../src/components/case/casemgt/index.js'), 'utf8')
const caseMgtStyles = fs.readFileSync(path.resolve(__dirname, '../src/components/case/casemgt/index.scss'), 'utf8')
const taskPage = fs.readFileSync(path.resolve(__dirname, '../src/pages/testTask/index.js'), 'utf8')
assert(caseMgt.includes('className="case-detail-back"'), '返回按钮应放在任务列表/任务详情左侧')
assert(caseMgt.includes("onClick={() => this.props.history.push('/case/caseList/1')}"), '返回按钮应固定返回用例列表，不能依赖浏览器历史')
assert(!caseMgt.includes('window.history.back()'), '返回按钮不应退回登录页等浏览器上一页')
assert(!caseMgt.includes('className="case-list-link"'), '详情页不应继续显示可点击的任务列表或用例列表')
assert(!caseMgt.includes('用例列表'), '用例编辑页和任务执行页不应显示“用例列表”文案')
assert(caseMgt.includes('className="case-detail-title"'), '标题区应只保留任务详情或用例详情')
assert(caseMgt.includes('用例名称：'), '编辑页和执行页标题应显示为用例名称')
assert(caseMgt.includes('className="case-detail-requirement"'), '关联需求应移动到详情标题同一行')
assert(caseMgtStyles.includes('grid-template-columns: repeat(4, minmax(0, 1fr));'), '返回、用例名称、关联需求和保存应平分同一行')
assert(caseMgt.includes('className="case-detail-save"'), '保存按钮应移动到详情页右上角')
assert(!editor.includes('className={`editor-save-actions'), '脑图右下角不应继续显示保存按钮')
assert(caseMgtStyles.includes('.case-detail-title {') && caseMgtStyles.includes('justify-self: center;'), '用例详情应位于标题行中间')
assert(caseMgtStyles.includes('.case-detail-requirement {') && caseMgtStyles.includes('justify-self: center;'), '关联需求应位于标题行第三等分区域')
assert(!caseMgt.includes('<Breadcrumb'), '详情标题不应继续使用可点击面包屑')
assert(!caseMgtStyles.includes('flex-direction: column;'), '返回按钮不应再单独占据标题上方一行')
assert(caseMgtStyles.includes('.case-detail-back.ant-btn-link') && caseMgtStyles.includes('color: #3370ff;'), '返回按钮应使用蓝色')
assert(caseMgtStyles.includes('padding: 0 12px 12px;'), '在线人数所在工具栏应整体上移')
assert(taskPage.includes("padding: '0 24px 24px'"), '详情页整体应向上移动一个返回按钮高度')
assert(editor.includes('className="mindmap-online-button"'), '在线人数按钮应使用统一圆角样式')
assert(styles.includes('.mindmap-header-search') && styles.includes('border-radius: 8px;'), '用例搜索框应使用 8px 圆角')
assert(styles.includes('.mindmap-online-button.ant-btn-primary'), '在线人数按钮应提供独立的圆角样式')
assert(caseMgtStyles.includes('.case-detail-save.ant-btn-primary') && caseMgtStyles.includes('border-radius: 10px;'), '顶部保存按钮应提供统一的圆角样式')
assert(styles.includes('.testcasemanage-lock.ant-switch') && styles.includes('.ant-switch-inner'), '锁定和解锁图标应在开关内部居中')
assert(styles.includes('.ws-warning .ant-modal-content'), 'Web 通信断开弹窗应使用独立的 Chrome 风格圆角')
assert(styles.includes('.ws-warning .ant-btn-primary'), 'Web 通信断开弹窗按钮应使用更大的圆角')
assert(panel.includes('createExecutionResultIndex'), '执行悬浮窗应建立结果索引，避免每次选中都遍历整棵树')
assert(!panel.includes('const counts = countExecutionResults(this.props.minder.getRoot())'), '渲染执行进度时不应重新遍历整棵树')
assert(editor.includes('caseContent: \'\''), '执行结果和备注应使用增量补丁，避免发送完整大型脑图')
assert(editor.includes('onExecutionChange={this.handleExecutionChange}'), '执行悬浮窗变更应走增量更新通道')
const progressCommand = core.slice(core.indexOf("var ProgressCommand"), core.indexOf("commands: {\n            progress"))
assert(progressCommand.includes('if (!km._largeMindMap) km.layout();'), '大型脑图标记结果时不应触发整树布局')
assert(core.includes('if (!node.getMinder()._largeMindMap) node.getMinder().layout(300);'), '大型脑图保存备注时不应触发整树布局')

console.log('execution UI regression checks passed')
